annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Speedscale Operator
  catalog.cattle.io/release-name: speedscale-operator
apiVersion: v1
appVersion: v0.9.24
description: The Speedscale Operator
home: https://speedscale.com
icon: https://github.com/speedscale/speedscale/raw/main/logo/gold_logo_only.png
keywords:
- speedscale
- test
- testing
- regression
- reliability
- load
- replay
- network
- traffic
kubeVersion: '>= 1.17.0-0'
maintainers:
- email: support@speedscale.com
  name: Speedscale Support
name: Speedscale Operator
version: 0.1.0
